version: "3.7"
services:
  speedstest-worker:
    build: .
    
    depends_on:
      - elk
    restart: always


  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
    restart: always